name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          sudo apt-get install mingw-w64 
      - name: Build executable
        run: |
          pyinstaller --onefile --target-arch=win64 main.py
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: exe
          path: /home/runner/work/Onekey
